name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: deploy
      run: |
        git config --global user.name "n8n - deploy"
        git config --global user.email "jan@n8n.io"
        git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/janober/n8n-docs.git"
        npm install
        ./deploy.sh
